version: '3.8'

services:
  mongodb-setup:
    build: .
    container_name: mongodb-atlas-setup
    env_file: .env
    networks:
      - mongodb-network
    restart: "no"  # Ne redémarre pas après l'exécution
    depends_on:
      mongodb:
        condition: service_healthy

  mongodb-populate:
    build: .
    container_name: mongodb-populate
    command: npm run populate
    env_file: .env
    networks:
      - mongodb-network
    restart: "no"
    depends_on:
      mongodb:
        condition: service_healthy

  # Service MongoDB local pour les tests
  mongodb:
    image: mongo:latest
    container_name: mongodb-local
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - mongodb_data:/data/db
    networks:
      - mongodb-network
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

networks:
  mongodb-network:
    driver: bridge

volumes:
  mongodb_data:
